### ISSUE TITLE
Issues with maps not loading and maps colliding with vanilla world.

### ISSUE THREAD

**Issue by deliciousburrito** [DEVBenSon/FiveM-Drift-Map-Pack#3]
Hi,

I am having a couple of issues with this pack:

Some maps are not loading in at all such as the Nurburgring and Akagipass.

Ebisu West Nishi is all inside of the main world, and needs to be higher in the air.

I have attached pictures of the problems.

https://imgur.com/a/Lwc6OCD

**Comment by DEVBenSon** [comment]
These maps were designed for the main GTA map to be removed.
